apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  namespace: kubedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo  
  template:
    metadata:
      labels:
        app: demo
    spec:    
      containers:
        - name: demo        
          image: reg.zmalloc.org:5000/rocket
          livenessProbe:
            httpGet:
              port: http
              path: /hello
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3          
          readinessProbe:
            httpGet:
              path: /hello
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 3
          ports:
          - containerPort: 8000
      
